import { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  ru: {
    header: {
      search: 'Поиск',
      catalog: 'Каталог',
      cart: 'Корзина',
      login: 'Вход',
      register: 'Регистрация',
      logout: 'Выйти',
      profile: 'Профиль',
    },
    home: {
      title: '',
      subtitle: '',
      popularProducts: 'Рекомендованные товары',
      allProducts: 'Все товары',
    },
    loading: 'Загрузка...',
    back: 'Назад',
    forward: 'Вперёд',
    productsNotFound: 'Товары не найдены',
    filterToggle: 'Фильтры',
    filterReset: 'Сбросить',
    filterMinPrice: 'Цена от',
    filterMaxPrice: 'Цена до',
    filterSort: 'Сортировка',
    filterDefault: 'По умолчанию',
    filterPriceAsc: 'Сначала дешёвые',
    filterPriceDesc: 'Сначала дорогие',
    filterFound: 'Найдено',
    filterOf: 'из',
    filterSortAsc: '↑',
    filterSortDesc: '↓',
    admin: {
      panel: 'Админ-панель',
      products: 'Товары',
      users: 'Пользователи',
      orders: 'Заказы',
      stats: 'Статистика',
      totalUsers: 'Пользователей',
      totalOrders: 'Заказов',
      totalRevenue: 'Общий доход',
      averageCheck: 'Средний чек',
      regularUsers: 'Обычные пользователи',
      administrators: 'Администраторы',
      ordersList: 'Заказы пользователя',
      noOrders: 'У пользователя пока нет заказов',
      noRegisteredUsers: 'Пока нет зарегистрированных пользователей',
      noOrdersYet: 'Пока нет заказов',
      viewOrders: 'Заказы',
      addProduct: '+ Добавить товар',
      cancel: 'Отмена',
      editProduct: 'Редактировать товар',
      newProduct: 'Новый товар',
      save: 'Сохранить',
      create: 'Создать',
      deleteConfirm: 'Удалить этот товар?',
      productUpdated: 'Товар обновлён',
      productCreated: 'Товар создан',
      productDeleted: 'Товар удален',
      productSaveError: 'Ошибка сохранения',
      productsTableId: 'ID',
      productsTableImage: 'Изображение',
      productsTableName: 'Название',
      productsTableCategory: 'Категория',
      productsTablePrice: 'Цена',
      productsTableStock: 'Остаток',
      productsTableActions: 'Действия',
      edit: 'Редактировать',
      delete: 'Удалить',
      userRegistered: 'Зарегистрирован',
      orderNumber: 'Заказ #',
      orderDate: 'Дата',
      customer: 'Покупатель',
      account: 'Аккаунт',
      total: 'Итого',
      role: 'Роль',
      unknown: 'Неизвестно',
      productsDescription: 'Описание',
    },
    cart: {
      title: 'Корзина',
      empty: 'Корзина пуста',
      emptyDescription: 'Добавьте товары для начала покупок',
      continueShopping: 'Продолжить покупки',
      total: 'Итого',
      checkout: 'Оформить заказ',
    },
    product: {
      addToCart: 'Добавить в корзину',
      added: 'Добавлено в корзину',
      description: 'Описание',
      inStock: 'В наличии',
      quantity: 'Количество',
      back: 'Назад к товарам',
      notFound: 'Товар не найден',
      sales: '🔥',
    },
    profile: {
      title: 'Профиль',
      purchaseHistory: 'История покупок',
      noPurchases: 'У вас пока нет покупок',
      goToProducts: 'Перейти к товарам',
      notAuthorized: 'Вы не авторизованы',
      loginRequired: 'Войдите в аккаунт, чтобы видеть историю покупок',
      changePassword: 'Изменить пароль',
    },
    auth: {
      email: 'Email',
      password: 'Пароль',
      currentPassword: 'Текущий пароль',
      newPassword: 'Новый пароль',
      confirmPassword: 'Подтвердите пароль',
      passwordMismatch: 'Пароли не совпадают',
      passwordChanged: 'Пароль успешно изменен',
      loginTitle: 'Войти',
      registerTitle: 'Регистрация',
      noAccount: 'Нет аккаунта?',
      hasAccount: 'Уже есть аккаунт?',
      registerNow: 'Зарегистрироваться',
      loginNow: 'Войти',
      forgotPassword: 'Забыли пароль?',
    },
    checkout: {
      title: 'Оформление заказа',
      contactInfo: 'Контактные данные',
      fullName: 'ФИО',
      phone: 'Телефон',
      email: 'Email',
      order: 'Заказ',
      pay: 'Оплатить',
      processing: 'Обработка...',
      success: 'Оплата успешна!',
      successMessage: 'Спасибо за покупку. Подтверждение отправлено на email.',
    },
    categories: {
      certificates: { name: 'Сертификаты', description: 'VPN, прокси и другие' },
      accounts: { name: 'Аккаунты', description: 'Аккаунты сервисов' },
      software: { name: 'ПО', description: 'Лицензионное ПО' },
      games: { name: 'Игры', description: 'Игровые ключи' },
      subscriptions: { name: 'Подписки', description: 'Стриминговые сервисы' },
      other: { name: 'Другое', description: 'Прочие товары' },
    },
    languages: {
      ru: 'Русский',
      en: 'English',
    },
    footer: {
      brand: 'SKAM',
      subtitle: 'Цифровые товары и услуги',
      categories: 'Каталог',
      info: 'Информация',
      about: 'О нас',
      terms: 'Условия использования',
      privacy: 'Политика конфиденциальности',
      contact: 'Контакты',
      support: 'Поддержка',
      email: 'support@skam.com',
      telegram: 'Telegram: @skam_support',
      copyright: '2025 SKAM. Все права защищены.',
    },
  },
  en: {
    header: {
      search: 'Search',
      catalog: 'Catalog',
      cart: 'Cart',
      login: 'Sign In',
      register: 'Register',
      logout: 'Sign Out',
      profile: 'Profile',
    },
    home: {
      title: '',
      subtitle: '',
      popularProducts: 'Recommended Products',
      allProducts: 'All Products',
    },
    loading: 'Loading...',
    back: 'Back',
    forward: 'Forward',
    productsNotFound: 'Products not found',
    filterToggle: 'Filters',
    filterReset: 'Reset',
    changePassword: 'Change Password',
    filterMinPrice: 'Min Price',
    filterMaxPrice: 'Max Price',
    filterSort: 'Sort',
    filterDefault: 'Default',
    filterPriceAsc: 'Price: Low to High',
    filterPriceDesc: 'Price: High to Low',
    filterFound: 'Found',
    filterOf: 'of',
    filterSortAsc: '↑',
    filterSortDesc: '↓',
    passwordChanged: 'Password successfully changed',
    admin: {
      panel: 'Admin Panel',
      products: 'Products',
      users: 'Users',
      orders: 'Orders',
      stats: 'Statistics',
      totalUsers: 'Users',
      totalOrders: 'Orders',
      totalRevenue: 'Total Revenue',
      averageCheck: 'Average Check',
      regularUsers: 'Regular Users',
      administrators: 'Administrators',
      ordersList: 'User Orders',
      noOrders: 'User has no orders yet',
      noRegisteredUsers: 'No registered users yet',
      noOrdersYet: 'No orders yet',
      viewOrders: 'Orders',
      addProduct: '+ Add Product',
      cancel: 'Cancel',
      editProduct: 'Edit Product',
      newProduct: 'New Product',
      save: 'Save',
      create: 'Create',
      deleteConfirm: 'Delete this product?',
      productUpdated: 'Product updated',
      productCreated: 'Product created',
      productDeleted: 'Product deleted',
      productSaveError: 'Save error',
      productsTableId: 'ID',
      productsTableImage: 'Image',
      productsTableName: 'Name',
      productsTableCategory: 'Category',
      productsTablePrice: 'Price',
      productsTableStock: 'Stock',
      productsTableActions: 'Actions',
      edit: 'Edit',
      delete: 'Delete',
      userRegistered: 'Registered',
      orderNumber: 'Order #',
      orderDate: 'Date',
      customer: 'Customer',
      account: 'Account',
      total: 'Total',
      role: 'Role',
      unknown: 'Unknown',
      productsDescription: 'Description',
    },
    cart: {
      title: 'Shopping Cart',
      empty: 'Your cart is empty',
      emptyDescription: 'Add some products to get started',
      continueShopping: 'Continue Shopping',
      total: 'Total',
      checkout: 'Checkout',
    },
    product: {
      addToCart: 'Add to Cart',
      added: 'Added to Cart',
      description: 'Description',
      inStock: 'In Stock',
      quantity: 'Quantity',
      back: 'Back to Products',
      notFound: 'Product not found',
      sales: '🔥',
    },
    profile: {
      title: 'Profile',
      purchaseHistory: 'Purchase History',
      noPurchases: 'You have no purchases yet',
      goToProducts: 'Go to Products',
      notAuthorized: 'You are not authorized',
      loginRequired: 'Sign in to see your purchase history',
      changePassword: 'Change Password',
    },
    auth: {
      email: 'Email',
      password: 'Password',
      currentPassword: 'Current Password',
      newPassword: 'New Password',
      confirmPassword: 'Confirm Password',
      passwordMismatch: 'Passwords do not match',
      passwordChanged: 'Password successfully changed',
      loginTitle: 'Sign In',
      registerTitle: 'Register',
      noAccount: "Don't have an account?",
      hasAccount: 'Already have an account?',
      registerNow: 'Register Now',
      loginNow: 'Sign In',
      forgotPassword: 'Forgot Password?',
    },
    checkout: {
      title: 'Checkout',
      contactInfo: 'Contact Information',
      fullName: 'Full Name',
      phone: 'Phone',
      email: 'Email',
      order: 'Order',
      pay: 'Pay',
      processing: 'Processing...',
      success: 'Payment Successful!',
      successMessage: 'Thank you for your purchase. Confirmation sent to email.',
    },
    categories: {
      certificates: { name: 'Certificates', description: 'VPN, proxy and others' },
      accounts: { name: 'Accounts', description: 'Service accounts' },
      software: { name: 'Software', description: 'Licensed software' },
      games: { name: 'Games', description: 'Game keys' },
      subscriptions: { name: 'Subscriptions', description: 'Streaming services' },
      other: { name: 'Other', description: 'Other products' },
    },
    languages: {
      ru: 'Русский',
      en: 'English',
    },
    footer: {
      brand: 'SKAM',
      subtitle: 'Digital Products and Services',
      categories: 'Categories',
      info: 'Information',
      about: 'About Us',
      terms: 'Terms of Service',
      privacy: 'Privacy Policy',
      contact: 'Contact',
      support: 'Support',
      email: 'support@skam.com',
      telegram: 'Telegram: @skam_support',
      copyright: '2025 SKAM. All rights reserved.',
    },
  },
};

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('language') || 'ru';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key) => {
    const keys = key.split('.');
    let value = translations[language];
    
    for (const k of keys) {
      if (value && value[k] !== undefined) {
        value = value[k];
      } else {
        return key;
      }
    }
    
    return value;
  };

  const changeLanguage = (newLang) => {
    setLanguage(newLang);
  };

  return (
    <LanguageContext.Provider value={{ language, t, changeLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
};
